// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------
const SEARCH_URL = process.env.ACESTREAM_SEARCH_URL || 'http://acestream-engine:6878/search';
const STREAM_BASE_URL = process.env.ACESTREAM_STREAM_BASE || 'http://streaming-television.pavel-usanli.online:6878/ace/manifest.m3u8';
const PAGE_SIZE = parseInt(process.env.ACESTREAM_PAGE_SIZE || '10', 10);
const PLAYLIST_FILE = process.env.PLAYLIST_FILE || 'playlist.m3u8';
const CACHE_TTL = parseInt(process.env.PLAYLIST_TTL || '3600', 10); // seconds
const PORT = process.env.PORT || 8000;
const EXTERNAL_PLAYLISTS = [
  { url: 'https://iptv-org.github.io/iptv/languages/bul.m3u', label: 'github', group: 'Болгария' },
  { url: 'https://iptv-org.github.io/iptv/languages/ces.m3u', label: 'github', group: 'Чехия' },
  { url: 'https://iptv-org.github.io/iptv/index.m3u', label: 'github', group: 'github' },
];

const COUNTRY_MAP = {
  'ae': 'ОАЭ',
  'al': 'Албания',
  'am': 'Армения',
  'ar': 'Аргентина',
  'at': 'Австрия',
  'au': 'Австралия',
  'be': 'Бельгия',
  'bg': 'Болгария',
  'bo': 'Боливия',
  'br': 'Бразилия',
  'by': 'Беларусь',
  'ca': 'Канада',
  'cd': 'ДР Конго',
  'ch': 'Швейцария',
  'cl': 'Чили',
  'cm': 'Камерун',
  'cn': 'Китай',
  'co': 'Колумбия',
  'cy': 'Кипр',
  'cz': 'Чехия',
  'de': 'Германия',
  'dk': 'Дания',
  'ee': 'Эстония',
  'eg': 'Египет',
  'es': 'Испания',
  'et': 'Эфиопия',
  'fi': 'Финляндия',
  'fr': 'Франция',
  'gb': 'Великобритания',
  'ge': 'Грузия',
  'gp': 'Гваделупа',
  'gq': 'Экваториальная Гвинея',
  'gr': 'Греция',
  'hu': 'Венгрия',
  'id': 'Индонезия',
  'ie': 'Ирландия',
  'il': 'Израиль',
  'in': 'Индия',
  'int': 'Международные',
  'iq': 'Ирак',
  'ir': 'Иран',
  'it': 'Италия',
  'jo': 'Иордания',
  'jp': 'Япония',
  'kg': 'Киргизия',
  'kr': 'Южная Корея',
  'kz': 'Казахстан',
  'lb': 'Ливан',
  'lt': 'Литва',
  'lv': 'Латвия',
  'md': 'Молдавия',
  'mk': 'Северная Македония',
  'mx': 'Мексика',
  'nl': 'Нидерланды',
  'no': 'Норвегия',
  'nz': 'Новая Зеландия',
  'om': 'Оман',
  'pl': 'Польша',
  'ps': 'Палестина',
  'pt': 'Португалия',
  'qa': 'Катар',
  'ro': 'Румыния',
  'rs': 'Сербия',
  'ru': 'Россия',
  'sa': 'Саудовская Аравия',
  'se': 'Швеция',
  'sg': 'Сингапур',
  'si': 'Словения',
  'sk': 'Словакия',
  'sy': 'Сирия',
  'th': 'Таиланд',
  'tj': 'Таджикистан',
  'tm': 'Туркмения',
  'tr': 'Турция',
  'tw': 'Тайвань',
  'tz': 'Танзания',
  'ua': 'Украина',
  'us': 'США',
  'uz': 'Узбекистан',
  'vn': 'Вьетнам',
  'za': 'ЮАР',
};

const CATEGORY_MAP = {
  'amateur': 'Любительское',
  'argentina': 'Аргентина',
  'documentaries': 'Документальные',
  'educational': 'Познавательные',
  'emilia romagna': 'Эмилия-Романья',
  'entertaining': 'Развлекательные',
  'fashion': 'Мода',
  'informational': 'Информационные',
  'kameros': 'Камеры',
  'kids': 'Детские',
  'movies': 'Кино',
  'music': 'Музыка',
  'music_video': 'Музыкальные клипы',
  'other': 'Прочее',
  'radijas': 'Радио',
  'regional': 'Региональные',
  'religion': 'Религия',
  'sport': 'Спорт',
  'teleshop': 'Телемагазин',
  'tv': 'ТВ',
  'vari': 'Разное',
};

module.exports = {
  SEARCH_URL,
  STREAM_BASE_URL,
  PAGE_SIZE,
  PLAYLIST_FILE,
  CACHE_TTL,
  PORT,
  COUNTRY_MAP,
  CATEGORY_MAP,
  EXTERNAL_PLAYLISTS,
};
